version: "3.1"
services:
  # Create the RabbitMQ service
  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${HOME}/rabbitmq:/var/lib/rabbitmq
      - ${HOME}/rabbitmq:/var/log/rabbitmq
    restart: always
    networks:
      - stock-network
    environment:
      - RABBITMQ_DEFAULT_USER=stockmarket
      - RABBITMQ_DEFAULT_PASS=supersecret123
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 5

  # Create the Golang service for Producer
  producer:
    container_name: rmq-producer
    ports:
      - "5050:5050"
    build: ./stock-publisher
    restart: always
    depends_on:
      - message-broker
    networks:
      - stock-network

  # Create the Golang service for Consumer
  consumer:
    container_name: rmq-consumer
    ports:
      - "5051:5051"
    build: ./stock-consumer
    restart: always
    depends_on:
      - message-broker
      - mongodb_aapl
      - mongodb_msft
      - mongodb_tsla
    networks:
      - stock-network

  # Create the MongoDB service for aapl
  mongodb_aapl:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb_aapl
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    depends_on:
      - consumer
    volumes:
      - ${HOME}/mongodb_aapl:/data/db
    networks:
      - stock-network

  # Create the MongoDB service for msft
  mongodb_msft:
    image: mongo:latest
    ports:
      - "27018:27017"
    container_name: mongodb_msft
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    depends_on:
      - consumer
    volumes:
      - ${HOME}/mongodb_msft:/data/db
    networks:
      - stock-network

  # Create the MongoDB service for tsla
  mongodb_tsla:
    image: mongo:latest
    ports:
      - "27019:27017"
    container_name: mongodb_tsla
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    depends_on:
      - consumer
    volumes:
      - ${HOME}/mongodb_tsla:/data/db
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge
